version: '2'
services:
  app:
    image: node:alpine
    links:
      - db
    depends_on:
      - db
    volumes:
      - .:/app
      - ../node_modules:/app/node_modules
    environment:
      TZ: Asia/Jakarta
    working_dir: /app
    command: ['node', 'n1_sequelize_moment.js', '--no-deprecation']
  db:
    image: mariadb:10.2
    volumes:
      - mydb:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d
    environment:
      TZ: Asia/Jakarta
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
volumes:
  mydb: